from typing import overload


__imgui_version__: str = '1.92.2 WIP'

__imgui_version_num__: int = 19214

class ImVec2:
    @overload
    def __init__(self) -> None: ...

    @overload
    def __init__(self, arg0: float, arg1: float, /) -> None: ...

    @property
    def x(self) -> float: ...

    @x.setter
    def x(self, arg: float, /) -> None: ...

    @property
    def y(self) -> float: ...

    @y.setter
    def y(self, arg: float, /) -> None: ...

    def __str__(self) -> str: ...

    def __repr__(self) -> str: ...

class ImVec4:
    @overload
    def __init__(self) -> None: ...

    @overload
    def __init__(self, arg0: float, arg1: float, arg2: float, arg3: float, /) -> None: ...

    @property
    def x(self) -> float: ...

    @x.setter
    def x(self, arg: float, /) -> None: ...

    @property
    def y(self) -> float: ...

    @y.setter
    def y(self, arg: float, /) -> None: ...

    @property
    def z(self) -> float: ...

    @z.setter
    def z(self, arg: float, /) -> None: ...

    @property
    def w(self) -> float: ...

    @w.setter
    def w(self, arg: float, /) -> None: ...

    def __str__(self) -> str: ...

    def __repr__(self) -> str: ...

class ImFontAtlas:
    def __init__(self) -> None: ...

class ImGuiContext:
    def __init__(self, arg: ImFontAtlas, /) -> None: ...

def CreateContext(shared_font_atlas: ImFontAtlas | None = None) -> ImGuiContext: ...
